### ISSUE TITLE
Progressive Web App Checklist

### ISSUE THREAD

**Issue by maxtkc** [Aspine/aspine#21]
Copied from: https://developers.google.com/web/progressive-web-apps/checklist

- [x] Site is served over HTTPS
- [x] Pages are responsive on tablets & mobile devices
- [ ] All app URLs load while offline
- [ ] Metadata provided for Add to Home screen
- [x] First load fast even on 3G
- [ ] Site works cross-browser
- [ ] Page transitions don't feel like they block on the network
- [x] Each page has a URL
- [ ] Site's content is indexed by Google
- [ ] Schema.org metadata is provided where appropriate
- [ ] Social metadata is provided where appropriate
- [ ] Canonical URLs are provided when necessary
- [ ] Pages use the History API
- [x] Content doesn't jump as the page loads
- [ ] Pressing back from a detail page retains scroll position on the previous list page
- [x] When tapped, inputs aren't obscured by the on screen keyboard
- [ ] Content is easily shareable from standalone or full screen mode
- [x] Site is responsive across phone, tablet and desktop screen sizes
- [x] Any app install prompts are not used excessively
- [ ] The Add to Home Screen prompt is intercepted
- [ ] Site uses cache-first networking
- [ ] Site appropriately informs the user when they're offline
- [ ] Provide context to the user about how notifications will be used
- [x] UI encouraging users to turn on Push Notifications must not be overly aggressive
- [ ] Site dims the screen when permission request is showing
- [x] Push notifications must be timely, precise and relevant
- [ ] Provides controls to enable and disable notifications
- [ ] User is logged in across devices via Credential Management API
- [ ] ~~User can pay easily via native UI from Payment Request API~~
