### ISSUE TITLE
General feature roadmap

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#66]
**Update 26 Nov 2019: This issue has been deprecated in favor of the project ["2019-20 Roadmap"](https://github.com/Aspine/aspine/projects/2). Please use that project for any new changes or status updates. Thank you.**

Aspine Feature List To DO:

Schedule:
* [ ] Show what lunch you have in the schedule (based on period three class code) - @kdk1616 
* [ ] Map feature that plots a pin on the zone map so people know where they should go (roughly)

GPA Calculator (@notrodes):
* [ ] Percent 
* [ ] Unweighted (out of 4)
* [ ] Weighted (Out of 5 depending on AP, HN, or CP)
* [ ] GPA from full year - dependent on getting grades from other quarters (all years dependent on archiving feature)

Math with Grades (@kdk1616):
* [ ] Apply Test Corrections button 
* [ ] Predict feature (tells you what you need to get on the next test to get an A in the class)

* [ ] Get Grades from other Quarters (dependent on lazy loading)
* [ ] Refactor code with lazy loading (@psvenk) - #56

Bug Fixes:
* [ ] Icons for adding and removing assignments don’t show up (@psvenk)
* [ ] Clock is one hour ahead (daylight savings time)

Various

Archive: 
* [ ] Store grades so that you can get a cumulative GPA for all four years of High School

Messageboard integration:
* [ ] Make each class have a link to corresponding messageboard chat (Like aspen +)

(Notifications):
* [ ] Uses SQL database and php script to check 
- Already wrote a script, but we will deal with this later once we ask permission from school about storing Aspen credentials in our database…

Miscellaneous:
* [ ] Make Aspine work with other school districts
- Should not be too hard, just stop hard-coding aspen.cpsd.us
* [ ] "Remember me" using cookies (@notrodes)
* [ ] Privacy policy / cookie popup
* [ ] Clean up code (@notrodes, @Derp7777)

**Comment by notrodes** [comment]
- [ ] Promised based as opposed to callback based architecture
- [ ] Lets encrypt install scripts

**Comment by notrodes** [comment]
> * Already wrote a script, but we will deal with this later once we ask permission from school about storing Aspen credentials in our database…

Currently Aspine uses the nosql database redis, migrate?
